---
title: "OpenSnapsvisor v1.0.0"
subtitle: "github.com/ginger51011/midsommar-snapsvisor-23"
author: "Emil Eriksson (<emil@apkollen.se>) and Contributors"
geometry: margin=1in
header-includes:
  - \renewcommand*\familydefault{\ttdefault}
---
